### ISSUE TITLE
Performance / Stability improvements

### ISSUE THREAD

**Issue by captncraig** [bosun-monitor/bosun#1195]
Brainstorming here more than anything

- [ ] Have web read endpoints pull from read only schedule replica without needing lock. #1197 
- [x] Instrument template rendering times. #1196
- [ ] make schedule lock debug info availible via web
- [ ] make logs avaible via web
- [ ] reduce goroutines used for search indexing #1194 
- [ ] faster json serializers for opentsdb datapoints (https://github.com/pquerna/ffjson)
